// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordUser = `-- name: CreatePasswordUser :one
INSERT INTO users (email, display_name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, display_name
`

type CreatePasswordUserParams struct {
	Email        string      `json:"email"`
	DisplayName  string      `json:"display_name"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

type CreatePasswordUserRow struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) CreatePasswordUser(ctx context.Context, arg CreatePasswordUserParams) (CreatePasswordUserRow, error) {
	row := q.db.QueryRow(ctx, createPasswordUser, arg.Email, arg.DisplayName, arg.PasswordHash)
	var i CreatePasswordUserRow
	err := row.Scan(&i.ID, &i.Email, &i.DisplayName)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const getGoogleUserBySubject = `-- name: GetGoogleUserBySubject :one
SELECT u.id, u.email, u.display_name
FROM auth_identities ai
JOIN users u ON u.id = ai.user_id
WHERE ai.provider = 'google' AND ai.provider_subject = $1
`

type GetGoogleUserBySubjectRow struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) GetGoogleUserBySubject(ctx context.Context, providerSubject string) (GetGoogleUserBySubjectRow, error) {
	row := q.db.QueryRow(ctx, getGoogleUserBySubject, providerSubject)
	var i GetGoogleUserBySubjectRow
	err := row.Scan(&i.ID, &i.Email, &i.DisplayName)
	return i, err
}

const getUserBySessionTokenHash = `-- name: GetUserBySessionTokenHash :one
SELECT u.id, u.email, u.display_name
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetUserBySessionTokenHashRow struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) GetUserBySessionTokenHash(ctx context.Context, tokenHash string) (GetUserBySessionTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getUserBySessionTokenHash, tokenHash)
	var i GetUserBySessionTokenHashRow
	err := row.Scan(&i.ID, &i.Email, &i.DisplayName)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT id, email, display_name, password_hash
FROM users
WHERE email = $1
`

type GetUserForLoginRow struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	DisplayName  string      `json:"display_name"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
	)
	return i, err
}

const linkGoogleIdentity = `-- name: LinkGoogleIdentity :exec
INSERT INTO auth_identities (user_id, provider, provider_subject, email)
VALUES ($1, 'google', $2, $3)
ON CONFLICT (provider, provider_subject) DO NOTHING
`

type LinkGoogleIdentityParams struct {
	UserID          uuid.UUID `json:"user_id"`
	ProviderSubject string    `json:"provider_subject"`
	Email           string    `json:"email"`
}

func (q *Queries) LinkGoogleIdentity(ctx context.Context, arg LinkGoogleIdentityParams) error {
	_, err := q.db.Exec(ctx, linkGoogleIdentity, arg.UserID, arg.ProviderSubject, arg.Email)
	return err
}

const upsertGoogleUserByEmail = `-- name: UpsertGoogleUserByEmail :one
INSERT INTO users (email, display_name)
VALUES ($1, $2)
ON CONFLICT (email) DO UPDATE SET
    display_name = users.display_name
RETURNING id, email, display_name
`

type UpsertGoogleUserByEmailParams struct {
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
}

type UpsertGoogleUserByEmailRow struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) UpsertGoogleUserByEmail(ctx context.Context, arg UpsertGoogleUserByEmailParams) (UpsertGoogleUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, upsertGoogleUserByEmail, arg.Email, arg.DisplayName)
	var i UpsertGoogleUserByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.DisplayName)
	return i, err
}
