// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, sender_user_id, body)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, sender_user_id, body, is_read, created_at
`

type CreateMessageParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderUserID   uuid.UUID `json:"sender_user_id"`
	Body           string    `json:"body"`
}

type CreateMessageRow struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	SenderUserID   uuid.UUID          `json:"sender_user_id"`
	Body           string             `json:"body"`
	IsRead         bool               `json:"is_read"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ConversationID, arg.SenderUserID, arg.Body)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderUserID,
		&i.Body,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS (
    SELECT 1 FROM conversation_members
    WHERE conversation_id = $1 AND user_id = $2
)
`

type IsConversationMemberParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isConversationMember, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listConversationMembers = `-- name: ListConversationMembers :many
SELECT user_id
FROM conversation_members
WHERE conversation_id = $1
`

func (q *Queries) ListConversationMembers(ctx context.Context, conversationID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesPaginated = `-- name: ListMessagesPaginated :many
SELECT id, conversation_id, sender_user_id, body, is_read, created_at
FROM messages
WHERE conversation_id = $1
  AND ($2::timestamptz IS NULL OR created_at < $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListMessagesPaginatedParams struct {
	ConversationID  uuid.UUID          `json:"conversation_id"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	LimitCount      int32              `json:"limit_count"`
}

type ListMessagesPaginatedRow struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	SenderUserID   uuid.UUID          `json:"sender_user_id"`
	Body           string             `json:"body"`
	IsRead         bool               `json:"is_read"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMessagesPaginated(ctx context.Context, arg ListMessagesPaginatedParams) ([]ListMessagesPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listMessagesPaginated, arg.ConversationID, arg.BeforeCreatedAt, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesPaginatedRow
	for rows.Next() {
		var i ListMessagesPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderUserID,
			&i.Body,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessagesRead = `-- name: MarkMessagesRead :exec
UPDATE messages
SET is_read = true
WHERE conversation_id = $1
  AND sender_user_id <> $2
  AND is_read = false
`

type MarkMessagesReadParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderUserID   uuid.UUID `json:"sender_user_id"`
}

func (q *Queries) MarkMessagesRead(ctx context.Context, arg MarkMessagesReadParams) error {
	_, err := q.db.Exec(ctx, markMessagesRead, arg.ConversationID, arg.SenderUserID)
	return err
}
