// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationMember = `-- name: AddConversationMember :exec
INSERT INTO conversation_members (conversation_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddConversationMemberParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error {
	_, err := q.db.Exec(ctx, addConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const createSwipe = `-- name: CreateSwipe :exec
INSERT INTO swipes (actor_user_id, target_user_id, action)
VALUES ($1, $2, $3)
`

type CreateSwipeParams struct {
	ActorUserID  uuid.UUID `json:"actor_user_id"`
	TargetUserID uuid.UUID `json:"target_user_id"`
	Action       string    `json:"action"`
}

func (q *Queries) CreateSwipe(ctx context.Context, arg CreateSwipeParams) error {
	_, err := q.db.Exec(ctx, createSwipe, arg.ActorUserID, arg.TargetUserID, arg.Action)
	return err
}

const hasReciprocalLike = `-- name: HasReciprocalLike :one
SELECT EXISTS (
    SELECT 1 FROM swipes
    WHERE actor_user_id = $1 AND target_user_id = $2 AND action = 'like'
)
`

type HasReciprocalLikeParams struct {
	ActorUserID  uuid.UUID `json:"actor_user_id"`
	TargetUserID uuid.UUID `json:"target_user_id"`
}

func (q *Queries) HasReciprocalLike(ctx context.Context, arg HasReciprocalLikeParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasReciprocalLike, arg.ActorUserID, arg.TargetUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listConversationsForUser = `-- name: ListConversationsForUser :many
SELECT c.id AS conversation_id, c.match_id, c.created_at
FROM conversations c
JOIN conversation_members cm ON cm.conversation_id = c.id
WHERE cm.user_id = $1
ORDER BY c.created_at DESC
`

type ListConversationsForUserRow struct {
	ConversationID uuid.UUID          `json:"conversation_id"`
	MatchID        uuid.UUID          `json:"match_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListConversationsForUser(ctx context.Context, userID uuid.UUID) ([]ListConversationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listConversationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsForUserRow
	for rows.Next() {
		var i ListConversationsForUserRow
		if err := rows.Scan(&i.ConversationID, &i.MatchID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesForUser = `-- name: ListMatchesForUser :many
SELECT m.id AS match_id, c.id AS conversation_id, m.created_at
FROM matches m
JOIN conversations c ON c.match_id = m.id
WHERE m.user_low_id = $1 OR m.user_high_id = $1
ORDER BY m.created_at DESC
`

type ListMatchesForUserRow struct {
	MatchID        uuid.UUID          `json:"match_id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMatchesForUser(ctx context.Context, userLowID uuid.UUID) ([]ListMatchesForUserRow, error) {
	rows, err := q.db.Query(ctx, listMatchesForUser, userLowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesForUserRow
	for rows.Next() {
		var i ListMatchesForUserRow
		if err := rows.Scan(&i.MatchID, &i.ConversationID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConversationForMatch = `-- name: UpsertConversationForMatch :one
INSERT INTO conversations (match_id)
VALUES ($1)
ON CONFLICT (match_id) DO UPDATE SET match_id = EXCLUDED.match_id
RETURNING id
`

func (q *Queries) UpsertConversationForMatch(ctx context.Context, matchID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertConversationForMatch, matchID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertMatch = `-- name: UpsertMatch :one
INSERT INTO matches (user_low_id, user_high_id)
VALUES ($1, $2)
ON CONFLICT (user_low_id, user_high_id) DO UPDATE SET user_low_id = EXCLUDED.user_low_id
RETURNING id
`

type UpsertMatchParams struct {
	UserLowID  uuid.UUID `json:"user_low_id"`
	UserHighID uuid.UUID `json:"user_high_id"`
}

func (q *Queries) UpsertMatch(ctx context.Context, arg UpsertMatchParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertMatch, arg.UserLowID, arg.UserHighID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
