// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthIdentity struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Provider        string             `json:"provider"`
	ProviderSubject string             `json:"provider_subject"`
	Email           string             `json:"email"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID            uuid.UUID          `json:"id"`
	MatchID       uuid.UUID          `json:"match_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
}

type ConversationMember struct {
	ConversationID uuid.UUID          `json:"conversation_id"`
	UserID         uuid.UUID          `json:"user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Match struct {
	ID         uuid.UUID          `json:"id"`
	UserLowID  uuid.UUID          `json:"user_low_id"`
	UserHighID uuid.UUID          `json:"user_high_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	SenderUserID   uuid.UUID          `json:"sender_user_id"`
	Body           string             `json:"body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	IsRead         bool               `json:"is_read"`
}

type Profile struct {
	UserID    uuid.UUID          `json:"user_id"`
	Bio       string             `json:"bio"`
	Course    string             `json:"course"`
	Campus    string             `json:"campus"`
	BirthDate pgtype.Date        `json:"birth_date"`
	Visible   bool               `json:"visible"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProfilePhoto struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Url       string             `json:"url"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProfilePreference struct {
	UserID       uuid.UUID          `json:"user_id"`
	InterestedIn string             `json:"interested_in"`
	MinAge       int32              `json:"min_age"`
	MaxAge       int32              `json:"max_age"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Swipe struct {
	ID           uuid.UUID          `json:"id"`
	ActorUserID  uuid.UUID          `json:"actor_user_id"`
	TargetUserID uuid.UUID          `json:"target_user_id"`
	Action       string             `json:"action"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
