// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProfilePhotoByPosition = `-- name: DeleteProfilePhotoByPosition :one
DELETE FROM profile_photos
WHERE user_id = $1 AND position = $2
RETURNING id, user_id, url, position, created_at
`

type DeleteProfilePhotoByPositionParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Position int32     `json:"position"`
}

func (q *Queries) DeleteProfilePhotoByPosition(ctx context.Context, arg DeleteProfilePhotoByPositionParams) (ProfilePhoto, error) {
	row := q.db.QueryRow(ctx, deleteProfilePhotoByPosition, arg.UserID, arg.Position)
	var i ProfilePhoto
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getMyProfile = `-- name: GetMyProfile :one
SELECT
    u.id,
    u.email,
    u.display_name,
    COALESCE(p.bio, '') AS bio,
    COALESCE(p.course, '') AS course,
    COALESCE(p.campus, '') AS campus,
    p.birth_date,
    COALESCE(p.visible, false) AS visible
FROM users u
LEFT JOIN profiles p ON p.user_id = u.id
WHERE u.id = $1
`

type GetMyProfileRow struct {
	ID          uuid.UUID   `json:"id"`
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
	Bio         string      `json:"bio"`
	Course      string      `json:"course"`
	Campus      string      `json:"campus"`
	BirthDate   pgtype.Date `json:"birth_date"`
	Visible     bool        `json:"visible"`
}

func (q *Queries) GetMyProfile(ctx context.Context, id uuid.UUID) (GetMyProfileRow, error) {
	row := q.db.QueryRow(ctx, getMyProfile, id)
	var i GetMyProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.Course,
		&i.Campus,
		&i.BirthDate,
		&i.Visible,
	)
	return i, err
}

const getProfilePhotoByPosition = `-- name: GetProfilePhotoByPosition :one
SELECT id, user_id, url, position, created_at
FROM profile_photos
WHERE user_id = $1 AND position = $2
`

type GetProfilePhotoByPositionParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Position int32     `json:"position"`
}

func (q *Queries) GetProfilePhotoByPosition(ctx context.Context, arg GetProfilePhotoByPositionParams) (ProfilePhoto, error) {
	row := q.db.QueryRow(ctx, getProfilePhotoByPosition, arg.UserID, arg.Position)
	var i ProfilePhoto
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getPublicProfile = `-- name: GetPublicProfile :one
SELECT
    u.id,
    u.display_name,
    COALESCE(p.bio, '') AS bio,
    COALESCE(p.course, '') AS course,
    COALESCE(p.campus, '') AS campus,
    p.birth_date,
    COALESCE(p.visible, false) AS visible,
    COALESCE((SELECT url FROM profile_photos WHERE user_id = u.id ORDER BY position ASC LIMIT 1), '')::text AS photo_url
FROM users u
LEFT JOIN profiles p ON p.user_id = u.id
WHERE u.id = $1
`

type GetPublicProfileRow struct {
	ID          uuid.UUID   `json:"id"`
	DisplayName string      `json:"display_name"`
	Bio         string      `json:"bio"`
	Course      string      `json:"course"`
	Campus      string      `json:"campus"`
	BirthDate   pgtype.Date `json:"birth_date"`
	Visible     bool        `json:"visible"`
	PhotoUrl    string      `json:"photo_url"`
}

func (q *Queries) GetPublicProfile(ctx context.Context, id uuid.UUID) (GetPublicProfileRow, error) {
	row := q.db.QueryRow(ctx, getPublicProfile, id)
	var i GetPublicProfileRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Bio,
		&i.Course,
		&i.Campus,
		&i.BirthDate,
		&i.Visible,
		&i.PhotoUrl,
	)
	return i, err
}

const listDiscoveryProfiles = `-- name: ListDiscoveryProfiles :many
SELECT u.id, u.display_name, p.bio, p.course, p.campus, p.birth_date
FROM users u
JOIN profiles p ON p.user_id = u.id
WHERE p.visible = true
  AND u.id <> $1
  AND NOT EXISTS (
    SELECT 1 FROM swipes sw
    WHERE sw.actor_user_id = $1 AND sw.target_user_id = u.id
  )
ORDER BY p.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListDiscoveryProfilesParams struct {
	ID     uuid.UUID `json:"id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListDiscoveryProfilesRow struct {
	ID          uuid.UUID   `json:"id"`
	DisplayName string      `json:"display_name"`
	Bio         string      `json:"bio"`
	Course      string      `json:"course"`
	Campus      string      `json:"campus"`
	BirthDate   pgtype.Date `json:"birth_date"`
}

func (q *Queries) ListDiscoveryProfiles(ctx context.Context, arg ListDiscoveryProfilesParams) ([]ListDiscoveryProfilesRow, error) {
	rows, err := q.db.Query(ctx, listDiscoveryProfiles, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiscoveryProfilesRow
	for rows.Next() {
		var i ListDiscoveryProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Bio,
			&i.Course,
			&i.Campus,
			&i.BirthDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfilePhotos = `-- name: ListProfilePhotos :many
SELECT id, user_id, url, position, created_at
FROM profile_photos
WHERE user_id = $1
ORDER BY position ASC
`

func (q *Queries) ListProfilePhotos(ctx context.Context, userID uuid.UUID) ([]ProfilePhoto, error) {
	rows, err := q.db.Query(ctx, listProfilePhotos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProfilePhoto
	for rows.Next() {
		var i ProfilePhoto
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfileVisibility = `-- name: UpdateProfileVisibility :execrows
UPDATE profiles
SET visible = $2, updated_at = now()
WHERE user_id = $1
  AND char_length(course) > 0
  AND char_length(campus) > 0
`

type UpdateProfileVisibilityParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Visible bool      `json:"visible"`
}

func (q *Queries) UpdateProfileVisibility(ctx context.Context, arg UpdateProfileVisibilityParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProfileVisibility, arg.UserID, arg.Visible)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO profiles (user_id, bio, course, campus, birth_date)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
    bio = EXCLUDED.bio,
    course = EXCLUDED.course,
    campus = EXCLUDED.campus,
    birth_date = EXCLUDED.birth_date,
    updated_at = now()
`

type UpsertProfileParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	Bio       string      `json:"bio"`
	Course    string      `json:"course"`
	Campus    string      `json:"campus"`
	BirthDate pgtype.Date `json:"birth_date"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.Exec(ctx, upsertProfile,
		arg.UserID,
		arg.Bio,
		arg.Course,
		arg.Campus,
		arg.BirthDate,
	)
	return err
}

const upsertProfilePhoto = `-- name: UpsertProfilePhoto :one
INSERT INTO profile_photos (user_id, url, position)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, position) DO UPDATE SET
    url = EXCLUDED.url,
    created_at = now()
RETURNING id, user_id, url, position, created_at
`

type UpsertProfilePhotoParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Url      string    `json:"url"`
	Position int32     `json:"position"`
}

func (q *Queries) UpsertProfilePhoto(ctx context.Context, arg UpsertProfilePhotoParams) (ProfilePhoto, error) {
	row := q.db.QueryRow(ctx, upsertProfilePhoto, arg.UserID, arg.Url, arg.Position)
	var i ProfilePhoto
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
