// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const blockUser = `-- name: BlockUser :exec
INSERT INTO blocks (blocker_id, blocked_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type BlockUserParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.Exec(ctx, blockUser, arg.BlockerID, arg.BlockedID)
	return err
}

const deleteProfilePhotoByPosition = `-- name: DeleteProfilePhotoByPosition :one
DELETE FROM profile_photos
WHERE user_id = $1 AND position = $2
RETURNING id, user_id, url, position, created_at
`

type DeleteProfilePhotoByPositionParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Position int32     `json:"position"`
}

func (q *Queries) DeleteProfilePhotoByPosition(ctx context.Context, arg DeleteProfilePhotoByPositionParams) (ProfilePhoto, error) {
	row := q.db.QueryRow(ctx, deleteProfilePhotoByPosition, arg.UserID, arg.Position)
	var i ProfilePhoto
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getMyProfile = `-- name: GetMyProfile :one
SELECT
    u.id,
    u.email,
    u.display_name,
    COALESCE(p.bio, '') AS bio,
    COALESCE(p.course, '') AS course,
    COALESCE(p.campus, '') AS campus,
    p.birth_date,
    COALESCE(p.visible, false) AS visible
FROM users u
LEFT JOIN profiles p ON p.user_id = u.id
WHERE u.id = $1
`

type GetMyProfileRow struct {
	ID          uuid.UUID   `json:"id"`
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
	Bio         string      `json:"bio"`
	Course      string      `json:"course"`
	Campus      string      `json:"campus"`
	BirthDate   pgtype.Date `json:"birth_date"`
	Visible     bool        `json:"visible"`
}

func (q *Queries) GetMyProfile(ctx context.Context, id uuid.UUID) (GetMyProfileRow, error) {
	row := q.db.QueryRow(ctx, getMyProfile, id)
	var i GetMyProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.Course,
		&i.Campus,
		&i.BirthDate,
		&i.Visible,
	)
	return i, err
}

const getPreferences = `-- name: GetPreferences :one
SELECT interested_in, min_age, max_age
FROM profile_preferences
WHERE user_id = $1
`

type GetPreferencesRow struct {
	InterestedIn string `json:"interested_in"`
	MinAge       int32  `json:"min_age"`
	MaxAge       int32  `json:"max_age"`
}

func (q *Queries) GetPreferences(ctx context.Context, userID uuid.UUID) (GetPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getPreferences, userID)
	var i GetPreferencesRow
	err := row.Scan(&i.InterestedIn, &i.MinAge, &i.MaxAge)
	return i, err
}

const getProfilePhotoByPosition = `-- name: GetProfilePhotoByPosition :one
SELECT id, user_id, url, position, created_at
FROM profile_photos
WHERE user_id = $1 AND position = $2
`

type GetProfilePhotoByPositionParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Position int32     `json:"position"`
}

func (q *Queries) GetProfilePhotoByPosition(ctx context.Context, arg GetProfilePhotoByPositionParams) (ProfilePhoto, error) {
	row := q.db.QueryRow(ctx, getProfilePhotoByPosition, arg.UserID, arg.Position)
	var i ProfilePhoto
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getPublicProfile = `-- name: GetPublicProfile :one
SELECT
    u.id,
    u.display_name,
    COALESCE(p.bio, '') AS bio,
    COALESCE(p.course, '') AS course,
    COALESCE(p.campus, '') AS campus,
    p.birth_date,
    COALESCE(p.visible, false) AS visible,
    COALESCE((SELECT url FROM profile_photos WHERE user_id = u.id ORDER BY position ASC LIMIT 1), '')::text AS photo_url
FROM users u
LEFT JOIN profiles p ON p.user_id = u.id
WHERE u.id = $1
`

type GetPublicProfileRow struct {
	ID          uuid.UUID   `json:"id"`
	DisplayName string      `json:"display_name"`
	Bio         string      `json:"bio"`
	Course      string      `json:"course"`
	Campus      string      `json:"campus"`
	BirthDate   pgtype.Date `json:"birth_date"`
	Visible     bool        `json:"visible"`
	PhotoUrl    string      `json:"photo_url"`
}

func (q *Queries) GetPublicProfile(ctx context.Context, id uuid.UUID) (GetPublicProfileRow, error) {
	row := q.db.QueryRow(ctx, getPublicProfile, id)
	var i GetPublicProfileRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Bio,
		&i.Course,
		&i.Campus,
		&i.BirthDate,
		&i.Visible,
		&i.PhotoUrl,
	)
	return i, err
}

const isBlocked = `-- name: IsBlocked :one
SELECT EXISTS (
    SELECT 1 FROM blocks
    WHERE blocker_id = $1 AND blocked_id = $2
) AS blocked
`

type IsBlockedParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) IsBlocked(ctx context.Context, arg IsBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlocked, arg.BlockerID, arg.BlockedID)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const listDiscoveryProfiles = `-- name: ListDiscoveryProfiles :many
SELECT u.id, u.display_name, p.bio, p.course, p.campus, p.birth_date
FROM users u
JOIN profiles p ON p.user_id = u.id
LEFT JOIN profile_preferences pref ON pref.user_id = $1
WHERE p.visible = true
  AND u.id <> $1
  AND NOT EXISTS (
    SELECT 1 FROM swipes sw
    WHERE sw.actor_user_id = $1 AND sw.target_user_id = u.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $1 AND b.blocked_id = u.id)
       OR (b.blocker_id = u.id AND b.blocked_id = $1)
  )
  AND (
    pref.min_age IS NULL
    OR p.birth_date IS NULL
    OR EXTRACT(YEAR FROM AGE(p.birth_date)) BETWEEN COALESCE(pref.min_age, 18) AND COALESCE(pref.max_age, 99)
  )
ORDER BY p.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListDiscoveryProfilesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListDiscoveryProfilesRow struct {
	ID          uuid.UUID   `json:"id"`
	DisplayName string      `json:"display_name"`
	Bio         string      `json:"bio"`
	Course      string      `json:"course"`
	Campus      string      `json:"campus"`
	BirthDate   pgtype.Date `json:"birth_date"`
}

func (q *Queries) ListDiscoveryProfiles(ctx context.Context, arg ListDiscoveryProfilesParams) ([]ListDiscoveryProfilesRow, error) {
	rows, err := q.db.Query(ctx, listDiscoveryProfiles, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiscoveryProfilesRow
	for rows.Next() {
		var i ListDiscoveryProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Bio,
			&i.Course,
			&i.Campus,
			&i.BirthDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfilePhotos = `-- name: ListProfilePhotos :many
SELECT id, user_id, url, position, created_at
FROM profile_photos
WHERE user_id = $1
ORDER BY position ASC
`

func (q *Queries) ListProfilePhotos(ctx context.Context, userID uuid.UUID) ([]ProfilePhoto, error) {
	rows, err := q.db.Query(ctx, listProfilePhotos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProfilePhoto
	for rows.Next() {
		var i ProfilePhoto
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblockUser = `-- name: UnblockUser :exec
DELETE FROM blocks WHERE blocker_id = $1 AND blocked_id = $2
`

type UnblockUserParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) error {
	_, err := q.db.Exec(ctx, unblockUser, arg.BlockerID, arg.BlockedID)
	return err
}

const updateProfileVisibility = `-- name: UpdateProfileVisibility :execrows
UPDATE profiles
SET visible = $2, updated_at = now()
WHERE user_id = $1
  AND char_length(course) > 0
  AND char_length(campus) > 0
`

type UpdateProfileVisibilityParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Visible bool      `json:"visible"`
}

func (q *Queries) UpdateProfileVisibility(ctx context.Context, arg UpdateProfileVisibilityParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProfileVisibility, arg.UserID, arg.Visible)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPreferences = `-- name: UpsertPreferences :exec
INSERT INTO profile_preferences (user_id, interested_in, min_age, max_age)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    interested_in = EXCLUDED.interested_in,
    min_age       = EXCLUDED.min_age,
    max_age       = EXCLUDED.max_age,
    updated_at    = now()
`

type UpsertPreferencesParams struct {
	UserID       uuid.UUID `json:"user_id"`
	InterestedIn string    `json:"interested_in"`
	MinAge       int32     `json:"min_age"`
	MaxAge       int32     `json:"max_age"`
}

func (q *Queries) UpsertPreferences(ctx context.Context, arg UpsertPreferencesParams) error {
	_, err := q.db.Exec(ctx, upsertPreferences,
		arg.UserID,
		arg.InterestedIn,
		arg.MinAge,
		arg.MaxAge,
	)
	return err
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO profiles (user_id, bio, course, campus, birth_date)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
    bio = EXCLUDED.bio,
    course = EXCLUDED.course,
    campus = EXCLUDED.campus,
    birth_date = EXCLUDED.birth_date,
    updated_at = now()
`

type UpsertProfileParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	Bio       string      `json:"bio"`
	Course    string      `json:"course"`
	Campus    string      `json:"campus"`
	BirthDate pgtype.Date `json:"birth_date"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.Exec(ctx, upsertProfile,
		arg.UserID,
		arg.Bio,
		arg.Course,
		arg.Campus,
		arg.BirthDate,
	)
	return err
}

const upsertProfilePhoto = `-- name: UpsertProfilePhoto :one
INSERT INTO profile_photos (user_id, url, position)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, position) DO UPDATE SET
    url = EXCLUDED.url,
    created_at = now()
RETURNING id, user_id, url, position, created_at
`

type UpsertProfilePhotoParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Url      string    `json:"url"`
	Position int32     `json:"position"`
}

func (q *Queries) UpsertProfilePhoto(ctx context.Context, arg UpsertProfilePhotoParams) (ProfilePhoto, error) {
	row := q.db.QueryRow(ctx, upsertProfilePhoto, arg.UserID, arg.Url, arg.Position)
	var i ProfilePhoto
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
